### ISSUE TITLE
Fix mobile positioning with media query

### ISSUE THREAD

**Issue by andreassolberg** [andreassolberg/DiscoJuice#49]
Must fit within mobile display. This works, verify it across browser:

``` css
@media (max-width: 600px) {
    div.discojuice { 
        position: absolute;
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        margin: 0px;
        border-radius: 0px;
    }
}
```
